name: scheduling-env
channels:
  - pytorch
  - nvidia
  - defaults 
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - torchaudio
  - torchvision
  - graphviz>=2.50
  - gymnasium>=0.28
  - ipykernel>=6.28
  - ipython>=8.25
  - matplotlib>=3.8
  - networkx>=3.3
  - numpy>=1.26
  - pandas>=2.2
  - scipy>=1.13
  - sympy>=1.12
  - tqdm>=4.66
  - conda-forge::imageio>=2.34
  - conda-forge::tensorboard>=2.17
  - anaconda::jupyter>=1.0
  - pygraphviz>=1.9
  - python-graphviz>=0.20
  - black=24.4.2
  - pytest>=7.4
  - isort>=5.13
  - plotly>=5.22
  - conda-forge::python-kaleido>=0.2
  - conda-forge::stable-baselines3
