name: Unit Test Workflow 
run-name: ${{ github.actor }} is running unit tests.
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ci/scripts/start_ci_container.sh
      - run: ci/scripts/run_unit_tests.sh
      - run: ci/scripts/stop_ci_container.sh
