name: Unit Test Workflow 
run-name: ${{ github.actor }} is running unit tests.
on: [push]
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker ps
